### ISSUE TITLE
CI fails with "unable to access 'https://git.fedorahosted.org/git/beakerlib.git"

### ISSUE THREAD

**Issue by evverx** [systemd/systemd-centos-ci#11]
See https://github.com/systemd/systemd/pull/5521#issuecomment-283696545

`system-tests.sh` tries to [`git clone https://git.fedorahosted.org/git/beakerlib.git`](https://github.com/systemd/systemd-centos-ci/blob/master/slave/system-tests.sh#L6). This fails with:
```
fatal: unable to access 'https://git.fedorahosted.org/git/beakerlib.git/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received
```
According to https://fedoraproject.org/wiki/Infrastructure/Fedorahosted-retirement
> fedorahosted.org was retired on 2017-03-01. If you are viewinng this page, odds are it's after that date and you have been redirected here by attempting to go to some project on fedorahosted.org. If you are a user of a project formerly hosted at fedorahosted.org, please search for the new home the project you are interested in likely has. If you are a maintainer of a project formerly hosted at fedorahosted.org and need your data to migrate, see below.

cc @blaskovic

**Comment by evverx** [comment]
@sopos, is https://github.com/beakerlib/beakerlib the official beakerlib's repo?

**Comment by sopos** [comment]
yes, we migrated there from fedorahosted.

2. března 2017 20:17:29 SEČ, Evgeny Vereshchagin <notifications@github.com> napsal:
