### ISSUE TITLE
wireguard doesn't seem to be installed on Arch when systemd-networkd-test.py is run

### ISSUE THREAD

**Issue by evverx** [systemd/systemd-centos-ci#122]
To judge from "modprobe: FATAL: Module wireguard not found in directory /lib/modules/5.1.4-arch1-1-ARCH" I've just found in https://ci.centos.org/job/systemd-pr-build-vagrant/2065/artifact//systemd-centos-ci/artifacts_w3PKi7/vagrant-logs.FM4/vagrant-arch-testsuite.SYc/systemd-networkd-tests.py_PASS.log the wireguard kernel module wasn't installed and all the tests covering wireguard were skipped.

Originally I discovered it in https://github.com/systemd/systemd-centos-ci/pull/117 but I didn't want to bury it there because I kind of expect that discussion to be lengthy :-)

**Comment by mrc0mmand** [comment]
Thanks for catching this! Installing `wireguard-arch` should hopefully fix this.
