### ISSUE TITLE
Replace Vagrant with mkosi

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd-centos-ci#129]
This idea was proposed by @poettering a few months back, but I dismissed it due to missing dependencies on CentOS and other reasons - the main one being the need to bootstrap a whole system from scratch before each test. However, after the introduction of caching #101, the bootstrapping could be easily moved to a separate cron job, making `mkosi` a viable option.

Using `mkosi` would have several benefits, mainly ditching the number of [workarounds](https://github.com/systemd/systemd-centos-ci/blob/master/vagrant/vagrant-make-cache.sh#L56) around Vagrant, as well as making the whole image generation process under *our control*. One of the immediate issues would be the need to *backport* several dependencies to CentOS (like `pacman`), either adding them directly to EPEL or just to our [systemd-centos-ci copr repo](https://copr.fedorainfracloud.org/coprs/mrc0mmand/systemd-centos-ci/), which shouldn't be *that* hard.

Also, one of the indirect side-effect would be providing some test coverage for `mkosi` itself :-)

@evverx, @poettering, @keszybz any opinion on why or why not is this a good idea?

**Comment by keszybz** [comment]
> backport several dependencies to CentOS (like pacman)

I expect this would be just a matter of pointing copr at dist-git.

>  any opinion

I think we should switch *iff* mkosi fits the job better. I don't think we should push mkosi just because it's "our" tool.

**Comment by mrc0mmand** [comment]
> > backport several dependencies to CentOS (like pacman)
> 
> I expect this would be just a matter of pointing copr at dist-git.

That sounds promising. As I don't have sufficient Fedora packaging experience (even though I'd really like to get it someday), a guidance in this direction would be welcome :-)
> 
> > any opinion
> 
> I think we should switch _iff_ mkosi fits the job better. I don't think we should push mkosi just because it's "our" tool.

I'd say it does. The *ideal* CI workflow for the current Vagrant run is something like:

1) create a base image of a requested distribution (in this case Arch Linux) & run in under qemu/kvm
2) install build & test dependencies
3) clone, checkout, compile, and install the requested systemd revision
4) reboot & run the tests

The present solution is somewhat cumbersome, as we need to fetch a particular RPM from Vagrant website, compile the vagrant-libvirt plugin, download a pre-created Vagrant box which supports the libvirt provider, as it is usually outdated perform a system upgrade, and then follow the steps above.

I wouldn't be surprised if `mkosi` wasn't already involved in the generation of certain Vagrant boxes, so dropping the Vagrant layer should make things at least a bit simpler and more reliable. Hopefully, I'm not missing something fundamental.

**Comment by evverx** [comment]
@mrc0mmand it's up to you but if I maintained CentOS CI I wouldn't switch to mkosi because it doesn't seem to me that it's stable. Frankly, having looked at the issues I'd say it's abandoned. The tests were broken there for I don't know how long and were fixed about 20 days ago (not that they test much though).

Regarding Vagrant, it works on MacOS and Windows and the "arch/generic" box is compatible with all the virtualization technologies Vagrant supports, which makes it relatively easy to experiment with some parts of CentOS CI without adding another layer of virtualization you need to spin up a Linux VM just to run mkosi. Not that it matters here though.

**Comment by mrc0mmand** [comment]
Fair enough, thanks for the (really appreciated) feedback. I'll close this issue for now, but we can re-open it in the future if the situation changes.
