### ISSUE TITLE
systemd-networkd-tests.py timeouts

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd-centos-ci#140]
After https://github.com/systemd/systemd/pull/12968, systemd-networkd-tests.py randomly timeouts. See https://github.com/systemd/systemd/pull/12972 and https://github.com/systemd/systemd/pull/12973.

@mrc0mmand Could you extend the timeout?

**Comment by mrc0mmand** [comment]
Thanks for catching this! Will re-trigger the failed jobs in mentioned PR's to get complete results.

**Comment by yuwata** [comment]
Thank you!
