### ISSUE TITLE
Check for possible coredumps after running the testsuite

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd-centos-ci#160]
Let's incorporate `coredumpctl --since "..."` and `coredumpctl info --since "..."` into the CI to check if certain systemd subcomponents don't *silently* crash during the testing process. 

This should allow us to catch issues like https://github.com/systemd/systemd/pull/12957#issuecomment-520227344

**Comment by mattiasj-axis** [comment]
If gdbs "bt full" can be added to the logs on the backtraces I think that would be quite valuable as well, certainly makes debugging easier.
