### ISSUE TITLE
Generate gcov/lcov reports

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd-centos-ci#166]
Consider generating lgcov/lcov reports (like [this one](https://mrc0mmand.fedorapeople.org/systemd-lcov-full/)) regularly (e.g. once a day).

The report above was generated with:

```
LDFLAGS=-lgcov meson build -Dc_args='-fprofile-arcs -ftest-coverage' -Dtest=unsafe -Dslow-tests=true
lcov --no-external -c -i -d . --rc lcov_branch_coverage=1 -o systemd_base.info
ninja -C build test
lcov --no-external -c -d . --rc lcov_branch_coverage=1 -o systemd_test.info
lcov --no-external --rc lcov_branch_coverage=1 -a systemd_base.info -a systemd_test.info -o systemd_full.info

genhtml systemd_full.info --branch-coverage --legend --highlight -s --output-directory systemd_coverage
```

**Comment by evverx** [comment]
Even though I'm not sure whether coverage reports will be helpful given the way systemd is developed, I'll just leave a couple of links here just in case: https://codecov.io/ and https://coveralls.io/.
