### ISSUE TITLE
`test/test-network/systemd-networkd-tests.py` doesn't seem to be run on CentOS CI

### ISSUE THREAD

**Issue by evverx** [systemd/systemd-centos-ci#21]
The test that was added in https://github.com/systemd/systemd/pull/10147 is unlikely to pass on Cent OS in its current form because it doesn't seem to be aware of older kernels that don't support new features, but it would be great to make it work and run there anyway. I guess every time it fails a new issue can be opened at https://github.com/systemd/systemd/issues because it was said in https://github.com/systemd/systemd/pull/10144#issuecomment-423492043 that the test isn't supposed to be Fedora-specific.

**Comment by mrc0mmand** [comment]
I stumbled upon it when working on https://github.com/systemd/systemd-centos-ci/issues/14 but then it just completely slipped my mind. Adding it to the testsuite definitely makes sense. Also, thanks a lot for https://github.com/systemd/systemd/pull/10542#discussion_r229890756, that's definitely going to help!

**Comment by mrc0mmand** [comment]
Related upstream issue: https://github.com/systemd/systemd/issues/10617

**Comment by ssahani** [comment]
Make sure you have the kernel modules else it will fail . If don;t disable the tests
```
======================================================================
FAIL: test_ipvlan (__main__.NetworkdNetDevTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 218, in test_ipvlan
    self.assertTrue(self.link_exits('ipvlan99'))
AssertionError: False is not true

======================================================================
FAIL: test_vcan (__main__.NetworkdNetDevTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 260, in test_vcan
    self.assertTrue(self.link_exits('vcan99'))
AssertionError: False is not true

======================================================================
FAIL: test_vrf (__main__.NetworkdNetDevTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 253, in test_vrf
    self.assertTrue(self.link_exits('vrf99'))
AssertionError: False is not true
```

**Comment by ssahani** [comment]
```
======================================================================
FAIL: test_routing_policy_rule (__main__.NetworkdNetWorkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test-network/systemd-networkd-tests.py", line 425, in test_routing_policy_rule
    self.assertRegex(output, 'tos 0x08')
AssertionError: Regex didn't match: 'tos 0x08' not found in '0:\tfrom all lookup local \n111:\tfrom 192.168.100.18 tos throughput iif test1 oif test1 lookup 7 \n32766:\tfrom all lookup main \n32767:\tfrom all lookup default'

----------------------------------------------------------------------
Ran 53 tests in 500.610s
>

this can;t be reproduced in 

```
Linux Zeus 4.18.16-200.fc28.x86_64 #1 SMP Sat Oct 20 23:53:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by evverx** [comment]
@ssahani I commented on the modules in https://github.com/systemd/systemd/issues/10617. I think it would make sense to just continue the discussion there.

**Comment by mrc0mmand** [comment]
@evverx @ssahani thanks a lot for the fixes!

```
...
[TASK] test/test-network/systemd-networkd-tests.py
Waiting for PID 29670 to finish
...................................................
[RESULT] PASS (log file: /root/systemd-centos-ci/testsuite-logs.lGt/systemd-networkd-tests.py.log)

TEST SUMMARY:
-------------
PASSED: 28
FAILED: 0
TOTAL:  28
```

**Comment by evverx** [comment]
@mrc0mmand I've just added a new test case in https://github.com/systemd/systemd/pull/10631. It should be fine but it would be great if you could check it out just in case.

**Comment by evverx** [comment]
Ideally, the test shouldn't pass because it currently trigger a crash described at the end of https://github.com/systemd/systemd/issues/10629, but it's currently far from ideal :-)

**Comment by evverx** [comment]
@mrc0mmand thank you! That's reassuring :-)
