### ISSUE TITLE
`systemd-networkd-tests.py` tweaks

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd-centos-ci#23]
Given the outcome in https://github.com/systemd/systemd/issues/10908#issuecomment-441358798 let's decide if we want to use the proposed firewalld rule or to disable firewalld altogether.

cc @evverx

**Comment by evverx** [comment]
I think it depends. For example, selinux is turned off by `bootstrap.sh` altogether because it isn't possible to update the policy every time a new feature added to `systemd` or something is changed. If the same is applicable to `networkd` and the firewall (which I'm not sure of), then it should be turned off as well.

**Comment by evverx** [comment]
@mrc0mmand I think the tests that fail on CentOS CI could be skipped for now. Checking that `BUILD_URL` is set and contains `centos` would probably suffice. This would prevent introducing new failing tests and breaking the tests that are working now.

**Comment by evverx** [comment]
Or instead of skipping them it would probably even better to mark them as "expectedFailure" like we do when some kernel modules aren't available. Those kludges can be removed one by one when the corresponding tests are fixed I guess.

**Comment by mrc0mmand** [comment]
Marking them as `expectedFailure` sounds definitely better. If I recall correctly, @ssahani had some patches for this already prepared, so let's see if we can wrap it up somehow.

**Comment by evverx** [comment]
As far as I can tell, the test tends to become rusty pretty fast. I've just run it on Fedora 28 and one sub-test failed and an assertion saying that "Assertion 'netdev->manager' failed at ../src/network/netdev/netdev.c:601, function netdev_join(). Aborting." was triggered somewhere else along the way. I'm not sure how many more tests will start failing while we're waiting for fixes :-)

**Comment by mrc0mmand** [comment]
It would be a pity to introduce a flaky test after we finally managed to weed out flakiness from the current test suite... I guess with enough effort we could reduce the instability to minimum, the question is if there's somebody willing to put their effort in

**Comment by mrc0mmand** [comment]
So, after a quick discussion with @ssahani it would be really beneficial to stabilize network and networkd test for both upstream and downstream (RHEL8).

As discussed earlier, the most important test case right now is `systemd-networkd-test.py` which had several issues (not only) in the CentOS CI, see https://github.com/systemd/systemd/issues/10908. There were several proposed solutions for certain issues, so we should finally choose the ideal combination and possibly tweak the rest of the failing tests.

Another network-related and disabled test, from what I remember, is `test_exec_privatenetwork` from `src/test/test-execute.c`, see https://github.com/systemd/systemd/issues/10934.

**Comment by yuwata** [comment]
Just for the reference. Remaining failure is shown in https://github.com/systemd/systemd/pull/11599#issuecomment-458927244.

**Comment by yuwata** [comment]
Two failures should be fixed by https://github.com/systemd/systemd/pull/11637.

**Comment by mrc0mmand** [comment]
Thanks to @yuwata and https://github.com/systemd/systemd/pull/11678 all known issues have been fixed and the test seems to be pretty stable (according to the last few dozen runs), so I'll go ahead and close this issue.
