### ISSUE TITLE
Drop the Arch repo pin when linux >= 5.7.0 package is out

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd-centos-ci#250]
See:
 * https://github.com/systemd/systemd-centos-ci/commit/2c4249cc1a945d64ae807b3da5f9400f3630891e
 * https://github.com/systemd/systemd-centos-ci/pull/249
 * https://github.com/systemd/systemd/pull/15682

**Comment by mrc0mmand** [comment]
Also see:
 * https://bugs.archlinux.org/task/66526

**Comment by DaanDeMeyer** [comment]
5.6.11 is out with the fix.

**Comment by mrc0mmand** [comment]
It sure is, thanks for the heads up!

Did some quick testing and the issue seems to be gone, will prepare a patch shortly.
