### ISSUE TITLE
SUT gets occasionally stuck during boot

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd-centos-ci#42]
Few weeks ago I noticed that sometimes the SUT gets stuck during boot with the new systemd and has to be manually killed and rescheduled. After introducing the sanity check (#32), this problem *moved* to the VM, so we can at least see the boot logs.

Full log (warning, 2.5MB file): https://ci.centos.org/job/systemd-pr-build/4143/consoleText

As my systemd-debug-fu is not good enough, any help would be definitely more than welcome (@evverx , @keszybz, ...). There's something wrong with the journal setup, but I'm not sure what.

**Comment by mrc0mmand** [comment]
The machine gets stuck because it ends up in the emergency shell:

```
[    4.787974] systemd[1]: Child 1257 (systemctl) died (code=killed, status=15/TERM)
[    4.789234] systemd[1]: initrd-switch-root.service: Child 1257 belongs to initrd-switch-root.service.
[    4.790735] systemd[1]: initrd-switch-root.service: Main process exited, code=killed, status=15/TERM
[    4.792412] systemd[1]: initrd-switch-root.service: Failed with result 'signal'.
[    4.793625] systemd[1]: initrd-switch-root.service: Changed start -> failed
[    4.794920] systemd[1]: initrd-switch-root.service: Job 186 initrd-switch-root.service/stop finished, result=done
[    4.796592] systemd[1]: Stopped Switch Root.
[[0;32m  OK  [0m] Stopped [0;1;39mSwitch Root[0m.

[    4.798293] systemd[1]: initrd-switch-root.service: Unit entered failed state.
[    4.799470] systemd[1]: initrd-switch-root.service: Triggering OnFailure= dependencies.
[    4.800771] systemd[1]: emergency.target: Trying to enqueue job emergency.target/start/replace-irreversibly
```

**Comment by evverx** [comment]
This looks like the issue mentioned in https://github.com/systemd/systemd/commit/a4021390fef27f4136497328f2e35 and might have been a side effect of `v219` in initrd trying to transition to `v240`  without https://github.com/systemd/systemd/commit/acc28e2e3037d689d6481e4664925cf31d4d087b#diff-dfef51899bfd19cdea6bc1f8d7b97e9f backported.

**Comment by mrc0mmand** [comment]
Thanks a lot for the references. I kind of hoped this wasn't caused by the 219 initrd, as that would mean the *original* issue is something different, but I somehow suspected it. I'll try to either tweak the dracut configuration, so it uses modules from the build directory, or just go all in and install the new systemd right after the compilation.

**Comment by evverx** [comment]
My wild guess would be that the original issue has something to do with a few udev regressions introduced relatevily recently. Hopefully it will go away as soon as all of them are fixed :-)

**Comment by mrc0mmand** [comment]
Let's close this issue in favor of https://github.com/systemd/systemd-centos-ci/pull/47
