### ISSUE TITLE
coveralls: udevd in systemd-networkd-tests.py seems not handled

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd-centos-ci#482]
We have several tests for udevd in systemd-networkd-tests.py, but it seems these are not counted.
See https://coveralls.io/builds/48001127/source?filename=src%2Fudev%2Fnet%2Flink-config.c.

**Comment by yuwata** [comment]
Also, TEST-64-STORAGE is not counted? While TEST-17-UDEV is counted.
https://coveralls.io/builds/48001127/source?filename=src%2Fudev%2Fudevd.c#L479

**Comment by mrc0mmand** [comment]
Oh well, it looks like coverage from udev workers is not accounted for. I'll look into it.
