### ISSUE TITLE
RFE: save per-test journal even on timeout

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd-centos-ci#615]
See https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-centos8/1294/artifact/systemd-centos-ci/index.html.

**Comment by mrc0mmand** [comment]
Should be addressed by a01fb1575fa672d14a950d2fa07c6556633e805f.

**Comment by yuwata** [comment]
Thank you!
