### ISSUE TITLE
Better to output journal with -o short-monotonic ?

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd-centos-ci#680]
When I try to tackle race like https://github.com/systemd/systemd/issues/30056, the 'complete' journal output is useful, but journalctl-testsuite_PASS.log does not show detailed timestamp, and hard to debug.
- dump journal with -o short-monotonic or something with higher precision.
- or, save journal file as is.

**Comment by mrc0mmand** [comment]
That definitely makes sense, and it's actually been in my todo list for a long time.
