### ISSUE TITLE
CentOS CI doesn't seem to support submodules

### ISSUE THREAD

**Issue by evverx** [systemd/systemd-centos-ci#90]
It's more of a comment :-) and given that in general submodules aren't used in `systemd`, I'm not sure whether it should be fixed or not. Anyway, as https://github.com/systemd/systemd/pull/12151 shows, submodules are a convenient way to start experimenting with libraries that aren't available (because they aren't packaged, for example). Currently CentOS CI is bailing out complaining that "src/libbpf/meson.build:5:0: ERROR: File bpf_next/src/libbpf/src/bpf.c does not exist." (which is helpful in the sense that it shows that something unusual is happening) but, maybe, it would be better if PRs like that could be built and went through the testing machinery. Something like "git submodule update --init --recursive" after PRs are checked out should suffice I think. @mrc0mmand could you have a look?

**Comment by mrc0mmand** [comment]
Good catch, thank you! I knew about the failing CI in this particular PR, but given that all CI's fail, I didn't bother delving deeper (which was a mistake as I can see). Supporting submodules is definitely a nice idea, as the CI is the right place to test things like not-yet-available libraries. Will fix it asap.
